include:
  - docker-compose.observability.yml

services:
  pgvector:
    image: pgvector/pgvector:pg17
    container_name: pgvector
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pgvector
      VECTOR_STORE_TYPE: pgVector
    volumes:
      - pgvector-db-data:/var/lib/postgresql/data
    networks:
      - net

volumes:
  pgvector-db-data: {}

networks:
  net:
    driver: bridge