name: Publish package to GitHub Packages
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - vector-db: chroma
            model-api: openai
            jar-base-name: mattermost-ai-service-openai-chroma
          - vector-db: chroma
            model-api: ollama
            jar-base-name: mattermost-ai-service-ollama-chroma

          - vector-db: pgvector
            model-api: openai
            jar-base-name: mattermost-ai-service-openai-pgvector
          - vector-db: pgvector
            model-api: ollama
            jar-base-name: mattermost-ai-service-ollama-pgvector

          - vector-db: redis
            model-api: openai
            jar-base-name: mattermost-ai-service-openai-redis
          - vector-db: redis
            model-api: ollama
            jar-base-name: mattermost-ai-service-ollama-redis

          - vector-db: weaviate
            model-api: openai
            jar-base-name: mattermost-ai-service-openai-weaviate
          - vector-db: weaviate
            model-api: ollama
            jar-base-name: mattermost-ai-service-ollama-weaviate
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: liberica
          java-version: 21
      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build artifact
        run: |
          ./mvnw versions:set -DnewVersion=${{ github.event.release.tag_name }} clean
          ./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout
          ./mvnw antrun:run -Dant.target=replace-artifactId "-Dartifact.id=${{ matrix.jar-base-name }}"
          ./mvnw help:evaluate -Dexpression=project.artifactId -q -DforceStdout
          ./mvnw package -Dvector-db-provider=${{ matrix.vector-db }} -Dmodel-api-provider=${{ matrix.model-api }}
          echo "Contents of target:"
          ls -l target
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.jar-base-name }}
          path: target/${{ matrix.jar-base-name }}-${{ github.event.release.tag_name }}.jar
          if-no-files-found: error
          retention-days: 1

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      checks: write
      actions: read
      issues: read
      packages: write
      pull-requests: read
      repository-projects: read
      statuses: read
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
      - name: Publish assets and generate release notes
        uses: softprops/action-gh-release@v2
        with:
          files: |
            */*.jar
          fail_on_unmatched_files: true
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}
